version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
        exclude-patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "androidx.compose.compiler*"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "androidx.compose.compiler*"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    schedule:
      interval: "daily"
